### ISSUE TITLE
Missing positional argument when defining middleware

### ISSUE THREAD

**Issue by JimLundin** [nitrictech/python-sdk#116]
### Issue
I get "Missing positional argument ...." error in mypy when trying to define middleware function

### Steps

When I define the following middleware function which returns an awaited HttpMiddleware object nxt(ctx): I get an error in mypy due to missing positional argument.

```{python}
from nitric.faas import HttpContext, HttpMiddleware

async def test(ctx: HttpContext, nxt: HttpMiddleware) -> HttpContext:
    return await nxt(ctx)
```
I get an error in mypy due to missing positional argument.

This is was done using the 0.13.0.dev6 version of the python package

I have created an example of the code in this repo: [example](https://github.com/JimLundin/middleware-example/blob/main/functions/hello.py)

### Expectations
Perhaps I have misconfigured something but I think that the correct return type for a middleware function should be HttpContext? In which case it seems that the nxt object should be supplied to the nxt call like this?

```{python}
from nitric.faas import HttpContext, HttpMiddleware

async def test(ctx: HttpContext, nxt: HttpMiddleware) -> HttpContext:
    return await nxt(ctx, nxt)
```

Which does indeed suppress the mypy error but seems redundant.

I tried looking at the source but I did not have the time to figure out the root cause

**Comment by jyecusch** [comment]
Hey @JimLundin you can pass `None` as the value for that nxt function and the type errors should be resolved.

```python
async def test(ctx: HttpContext, nxt: HttpMiddleware) -> HttpContext:
    return await nxt(ctx, None)
```

That said, this is a common scenario, I could look at making that argument a keyword argument that can be omitted

**Comment by jyecusch** [comment]
A new prerelease version `0.13.0.dev7` makes that nxt argument able to be omitted. Let us know if that works for you.

**Comment by JimLundin** [comment]
Hi @jyecusch,
Appreciate you looking into it! I have verified that using 0.13.0.dev7, this now works as I would expect from the documentation. 😄 
Closing the issue!
