### ISSUE TITLE
Bucket Notification Trigger functionality broken - missing some functions and validations

### ISSUE THREAD

**Issue by g-greatdevaks** [nitrictech/python-sdk#133]
### Issue
The bug is related to the bucket notification trigger functionality for Python.

**Code referenced:** https://nitric.io/docs/reference/python/storage/bucket-on

**Bug 1:**
In the code snippet shown below, the second argument to the decorator doesn't seem to be having any validation.
Any random value can be supplied to the second argument and it works.
**This does not seem to be an expected behaviour. Only a valid path should be allowed.**
```
@assets.on("write", "/images/cat")
async def create_cat_image(ctx):
  print(f"A cat image was written")
```

On checking the codebase, there doesn't seem to be any checks for notification_prefix_filter. The filter is most likely meant for filtering events containing the provided key (in form of the second argument).

**Bug 2:**
In the code snippet shown below, the bucket object `accessible_assets` (having permissions) doesn't have any attribute `on`.
```
@accessible_assets.on("write", "/images/dog")
async def access_dog_file(ctx):
  dog_image = await ctx.req.file.read()

  print(dog_image)
```
**Error for Bug 2:**
```
@accessible_assets.on("write", "/images/dog")
AttributeError: 'BucketRef' object has no attribute 'on'
Unclosed connection: Channel('localhost', 17501, ..., path=None)
```

The BucketRef class doesn't have any function for `on`. 

### Expected
The intended behaviour has already been described above.

### Nitric CLI Version:
1.37.6

**Comment by tjholm** [comment]
Thanks @g-greatdevaks 

I've written up a PR to add `on` to BucketRef here: https://github.com/nitrictech/python-sdk/pull/136

For Bug 1, what type of validation are you expecting? Is there are particular character set  that you would expect this to be limited to?

If we impose validation on the prefix, we'll likely implement it in a decorator for the nitric providers, in both the nitric CLI and core repositories so we can apply the same validation to all language implementations.

I'm assuming the kind of validation you're expecting would be some subset of the following:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html
https://cloud.google.com/storage/docs/objects
https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#unicode-characters-not-recommended-for-use-in-container-or-blob-names

Let me know if thats in line with what you were thinking.

**Comment by g-greatdevaks** [comment]
Thanks for the prompt response, @tjholm 💯
For **Bug 1**, I am a bit unclear about the functionality of the prefix filter key (the second argument).

Two types of validations I was thinking about (based on my understanding that the second argument is meant for such checks), as stated below:
1. Object name validation to match with the standards, as you rightly highlighted.
2. A check on the defined path (as per the example on the official document, the path looks similar to the hierarchy where the object is going to be stored in the Storage Bucket) - whether the path is valid or invalid.

**Comment by jyecusch** [comment]
@g-greatdevaks in the file/object stores we support objects are typically stored in a flat structure within their buckets, essentially they're key/value pairs. While using paths e.g. `image/latest/pic.png` is useful for organization and using the bucket as if they were a traditional file system, that's just a convention. There is a good write up of this in the [Google Cloud Storage docs](https://cloud.google.com/storage/docs/objects#namespace).

The way the prefix filter works is essentially a "starts with" check on file events. Any files that match the desired event type (e.g. "write" for first write) and has a key that starts with the provided prefix will match and trigger the function.

@tjholm given the object stores can be quite permissive with valid key values, I suspect the only safe limitation we could put on the prefix filter would be preventing strings containing newline/carriage characters. Most other characters appear to be valid in one store or another.

**Comment by jyecusch** [comment]
We found an issue with the prefix filtering on local environments which I expect caused the confusion, they were effectively not working. That's now fixed in the CLI. We've also added the missing `.on` function to the BucketRef like in other SDKs. If you try again now with CLI v1.38.1+  and Python SDK v1.0.4+ these issues should be resolved.

**Comment by g-greatdevaks** [comment]
Thanks for the prompt fix, Jye.
Yes, my concern was about the prefix filter operation not being respected.
Thanks for fixing it.
